export { LandingRouting } from './landing/routes'
export { AdminRoutes } from './admin/routes'
export { ClientRoutes } from './client/routes'
export { SellerRoutes } from './seller/routes'
export { ShoppingCartComponent } from './shopping/layout'
