export const ADD_NEW_SELLER = '[seller] ADD_NEW_SELLER'
export const ACTIVE_SELLER = '[seller] ACTIVE_SELLER'
export const EDIT_SELLER = '[seller] EDIT_SELLER'
export const SUSPENSE_SELLER = '[seller] SUSPENSE_SELLER'
export const GET_SELLERS = '[seller] GET_SELLERS'
export const SET_TOTAL_REGISTROS_SELLER = '[seller] TOTAL_REGISTROS'
export const GET_ALL_SELLERS = '[seller] ALL_SELLERS'
